services:
  mariadb:
    container_name: "${COMPOSE_PROJECT_NAME}_mariadb"
    image: mariadb:latest
    ports:
      - "3307:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=mydb

  redis:
    container_name: "${COMPOSE_PROJECT_NAME}_redis"
    image: redis:latest
    ports:
      - "6379:6379"

  webapp:
    container_name: "${COMPOSE_PROJECT_NAME}_webapp"
    build: .
    depends_on:
      - mariadb
      - redis
    ports:
      - "8080:80"

