version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: my-mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=mydb
    ports:
      - "3307:3306"

  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - "6379:6379"

  webapp:
    build: .
    container_name: my-webapp
    depends_on:
      - mariadb
      - redis
    ports:
      - "8080:80"
