version: "3.8"

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "0:80" # Dynamische externe Port-Zuweisung
    container_name: ${PROJECT_NAME}_webapp
    restart: always
